### ISSUE TITLE
Automatic scrolling

### ISSUE THREAD

**Issue by FerasAmara** [5sw/SWParallaxScrollView#1]
Hi @5sw 

I want to make it with automatic horizontal scrolling, like angry bird game background, can you help me with that?

Regards,
Feras Amara

**Comment by 5sw** [comment]
I am not sure if it makes sense to directly build this functionality into the library. What is your use-case for this and what are the exact requirements?

This can be implemented very easily by creating a timer that fires for every frame and moves the contentOffset along in the right direction. To get a smooth animation it would be best to use CADisplayLink so the timer is linked to the actual screen refresh rate. Using this approach also provides the greatest control over the animation.

Using UIView animations to update the content offset with animation doesn’t work as it moves all layers at the same speed.

**Comment by FerasAmara** [comment]
Thank you @5sw  for your reply, first of all, the application I want to develop is for kids, so I want to make it more like games backgrounds.

I'm sorry but I didn't get it, I tried to put a break point in the method
- (void)tapped: (id)sender {
  [(SWParallaxScrollView *)self.view setContentOffset:CGPointMake(0, 0) animated:YES];
  }
  but the breakpoint doesn't stopped there, could you please help me

**Comment by 5sw** [comment]
The gesture recognizer is configured for a tap with two fingers (see the end of the loadView method), so the tapped method doesn’t get called in the simulator or when tapping with only one finger on the device.

**Comment by FerasAmara** [comment]
@5sw I couldn't make it auto scrolling, if you can make it for me and send me your sample project at ( f.amara@ats-ware.com ) , or (  feras.amara@hotmail.com ) , I really appreciate your help. 

Many and big thanks,
Best Regards.
